"""The acceptance criterion, written down before it is met.

This file exists to be diffable. If the bar ever moves, `git log` shows who
moved it, when, and whether the move happened before or after the number it
governs was measured. A threshold chosen after seeing the result is not a
threshold, and the only defence against that is a dated record.

PROVENANCE -- this is not a new bar invented for this module
--------------------------------------------------------------
Every clause below restates a standard the repo already held:

  (1) beat the null          `docs/QUALITY.md` review checklist item 5 requires
                             the comparison against nulls be reported beside
                             every benchmark. `screen/__init__.py` already
                             refuses to rank on exactly this basis: "Until that
                             inverts, a predicted effect size is not
                             information."

  (2) on the subset that     `backtest/loo.py` documents that active-comparator
      can discriminate       arms predict exactly 0% at every strength, so their
                             error measures the rule's shape and not its
                             calibration. A headline that improves only because
                             those arms moved has not learned anything, so the
                             placebo-controlled subset must improve too.

  (3) survive resampling     `docs/QUALITY.md` item 6 asks for the
                             measurement-noise ceiling. With 12 quantified arms
                             and 5 mechanism folds, a bare inversion of two
                             means is inside the noise. The paired bootstrap is
                             the cheapest honest guard.

  (4) both scorers, not      A candidate generated by the screen is a NEW
      the friendlier one     mechanism, so leave-one-mechanism-out is the test
                             that grades it. LOO alone would let a mechanism the
                             model has never seen inherit a score earned on
                             mechanisms it has.

  (5) missing evidence is    An unmeasured scorer is not a passed scorer. An
      not a pass             UNMEASURED certificate can only ABSTAIN.

MARGIN, AND WHY IT IS 0.20
---------------------------
`MIN_RELATIVE_MARGIN = 0.20` asks the predictor to cut the null's error by a
fifth before its output counts as information. It is a judgement call, and the
honest description of where it comes from: `backtest/lomo.py` reports a
bootstrapped noise floor of "roughly 10%" on its numbers, so a 20% margin is
that floor with a factor of two on it. It is not derived from a power
calculation, and no candidate's fate currently depends on its exact value --
both scorers presently sit on the wrong side of zero, which is 20 points before
this constant is reached.

NOT IN THIS CRITERION, DELIBERATELY
------------------------------------
No clause about effect size, novelty, or safety. The device cannot rank (see
`screen/__init__.py`), so "how good is it" is not a question it may ask. Harm
is handled where the evidence lives: `bricks/harm_channel.py` flags a
Treg-biased target as a SOFT liability at p = 0.067 on six targets, which
`screen/kill_filter.py` correctly refuses to let veto anything. Importing that
flag into a pass/fail rule would give it exactly the authority its own p-value
says it has not earned.
"""

from __future__ import annotations

from dataclasses import dataclass

# Date the criterion was fixed. Kept as a string so it appears verbatim in
# every verdict's provenance and in any diff of this file.
CRITERION_FIXED_ON = "2026-09-20"


@dataclass(frozen=True)
class AcceptanceCriterion:
    """What a predictor must show before a PASS may be emitted from its scores."""

    fixed_on: str
    min_relative_margin: float
    bootstrap_resamples: int
    bootstrap_confidence: float
    require_placebo_subset: bool
    require_mechanism_holdout: bool

    def margin_met(self, mae: float, null_mae: float) -> bool:
        """Did the predictor cut the null's error by the required fraction?"""
        if null_mae <= 0:
            # A null with no error to cut cannot be beaten by a fraction of it.
            # This is a degenerate arm set, not a passing predictor.
            return False
        return (null_mae - mae) / null_mae >= self.min_relative_margin

    def describe(self) -> str:
        return (
            f"criterion fixed {self.fixed_on}: out-of-sample MAE must beat the "
            f"predict-the-mean null by >={self.min_relative_margin:.0%} on the full arm "
            f"set and on the placebo-controlled subset, the paired bootstrap "
            f"({self.bootstrap_resamples} resamples, {self.bootstrap_confidence:.0%} CI) "
            f"must exclude zero, and the mechanism-holdout scorer must be measured "
            f"and must also clear the bar"
        )


CRITERION = AcceptanceCriterion(
    fixed_on=CRITERION_FIXED_ON,
    min_relative_margin=0.20,
    bootstrap_resamples=10_000,
    bootstrap_confidence=0.95,
    require_placebo_subset=True,
    require_mechanism_holdout=True,
)
